apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs
  labels:
    {{- include "songs.labels" . | nindent 4}}
    app.kubernetes.io/component: songs
spec:
  replicas: {{ .Values.songs.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: songs
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: songs
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: songs
          image: {{ .Values.songs.image }}
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: ms-songs-mongodb
                  key: ms_songs_db_url
            - name: SPOTIFY_APP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: spotify
                  key: spotify_app_client_id
            - name: SPOTIFY_APP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spotify
                  key: spotify_app_client_secret
            - name: SUPPORT_HOST
              valueFrom:
                secretKeyRef:
                  name: ms-songs-hosts-secrets
                  key: support_host
            - name: USERS_HOST
              valueFrom:
                secretKeyRef:
                  name: ms-songs-hosts-secrets
                  key: users_host
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000