apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs
  labels:
    {{- include "songs.labels" . | nindent 4}}
    app.kubernetes.io/component: songs
spec:
  replicas: {{ .Values.songs.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: songs
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: songs
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: songs
          image: {{ .Values.songs.image }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000