apiVersion: v1
kind: Secret
metadata:
  name: ms-songs-hosts-secrets
  labels:
    app.kubernetes.io/component: ms-songs-hosts-secrets
    {{- include "songs.labels" . | nindent 4}}
type: Opaque
data:
  support_host: {{ .Values.supportHost | b64enc }}
  users_host: {{ .Values.usersHost | b64enc }}