apiVersion: v1
kind: Secret
metadata:
  name: ms-songs-jwt-secrets
  labels:
    app.kubernetes.io/component: ms-songs-jwt-secrets
    {{- include "songs.labels" . | nindent 4}}
type: Opaque
data:
  jwt_secret: {{ .Values.jwtSecret | b64enc }}