apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "songs.labels" . | nindent 4}}
type: Opaque
data:
  ms_songs_db_url: {{ .Values.msSongsMongoUrl | b64enc }}