apiVersion: v1
kind: Secret
metadata:
  name: spotify
  labels:
    app.kubernetes.io/component: spotify
    {{- include "songs.labels" . | nindent 4}}
type: Opaque
data:
  spotify_app_client_id: {{ .Values.spotifyAppClientId | b64enc }}
  spotify_app_client_secret: {{ .Values.spotifyAppClientSecret | b64enc }}