name: Okteto Deployment

on:
  push:
    branches: [main]

env:
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  test:
    uses: fisg4/ms-songs/.github/workflows/tests.yml@main
    secrets: inherit

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Okteto Login
        uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Okteto Deploy
        uses: resinas/okteto-push@v1.0.2
        with:
          namespace: fastmusik-marmolpen3
          build: true
